# hello numpy!
this page is for numpy, which is the foundation of Machine Learning,\
and also I should learn another site_package example **pandas** and **matplotlib**.\
Now let's coding:

## What's Numpy?
Multidimensional array object **ndarray** + efficient vectorized computation.

In [3]:
import numpy as np
a = [1, 2, 3]
b = [4, 5, 6]

print(f"list plus:", a + b, sep = "")

arra = np.array(a)
arrb = np.array(b)
print(f"np_array plus:", arra + arrb, sep = "")

list plus:[1, 2, 3, 4, 5, 6]
np_array plus:[5 7 9]


## Create arr

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
zeros = np.zeros((3, 4)) 
# initialize a dimensional-array with all zero in row 3 and column 4

ones = np.ones((2, 3))
# like np.zeros(), but all one

eye = np.eye(5)
# row 5 column 5 Identity martix

print(zeros)
print()
print(ones)
print()
print(eye)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
# arithmatic sequence
range_arr = np.arange(0, 10, 2) #
lin_arr = np.linspace(0, 1, 5) #
print(range_arr)
print()
print(lin_arr)

[0 2 4 6 8]

[0.   0.25 0.5  0.75 1.  ]


## Attribute

In [12]:
arr = np.array([[1,2,3],
               [4,5,6]])
print(f"the shape of arr(a row ,b column):   {arr.shape}")
print(f"dimension of arr :                   {arr.ndim}")
print(f"size of arr(count how much elements):{arr.size}")
print(f"type of data:                        {arr.dtype}")

reshaped = arr.reshape(3, 2)
print(f"reshaped the arr:(3 r 2 c)           \n{reshaped}")

the shape of arr(a row ,b column):   (2, 3)
dimension of arr :                   2
size of arr(count how much elements):6
type of data:                        int64
reshaped the arr:(3 r 2 c)           [[1 2]
 [3 4]
 [5 6]]


## index and slicing

In [16]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
# basic slicing : [start:end:step]
print(f"0 r 1 c : {arr[0, 1]}")
print(f"1 - 2 r 1 - 2 c:\n {arr[1:3, 1:3]}")

rows = [0, 1, 2]
cols = [1, 2, 3]
print(arr[rows, cols]) # find (0,1) (1,2) (2,3)

# bool index
print(arr[arr > 5])


0 r 1 c : 2
1 - 2 r 1 - 2 c:
 [[ 6  7]
 [10 11]]
[ 2  7 12]
[ 6  7  8  9 10 11 12]


# Vectorized computation

In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)
print(a ** 2)
print(np.sqrt(a))
# compare
print(a > 2)

# reduce
print(f"sums : {np.sum(a)}")
print(f"mean : {np.mean(a)}") # average
print(f"max  : {np.max(a)}")
print(f"std  : {np.std(a)}") # Standard Division
print(f"dot  : {np.dot(a, b)}") # Inner product

# Martix multiply (very important!!!!)
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A @ B)
print(np.matmul(A, B)) # like A @ B

[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]
[False False  True]
6
2.0
3
0.816496580927726
32
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


# Broadcasting
when one arr' shape different from another arr\
Numpy will expand smaller one

In [19]:
arr = np.array([1,2,3])
print(arr + 10) # [11, 12, 13]

row = np.array([1,2,3])
col = np.array([[4],[5],[6]])

print(row + col)


[11 12 13]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
arr = np.array([[1,2],[3,4]])
# 轴 (axis): axis = 0 (row), axis = 1 (col)
print(np.sum(arr, axis = 0)) # [4,6] by col
print(np.sum(arr, axis = 1)) # [3,7] by row

a = np.array([1,2])
b = np.array([3,4])
print(np.concatenate([a,b])) # by row
print(np.vstack([a,b])) # by col
print(np.hstack([a.reshape(2,1), b.reshape(2,1)])) 
view = arr[:]    # change view will change arr
copy = arr.copy()


[4 6]
[3 7]
[1 2 3 4]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


: 